### ISSUE TITLE
Connectionstring cannot be null -> it seems like it is not saved

### ISSUE THREAD

**Issue by TclasenITVT** [jhueppauff/Dynamics365-Customizing-Downloader#80]
![image](https://user-images.githubusercontent.com/35216119/39039757-630b2378-4486-11e8-9c96-e7a8b4eef70d.png)

Once you created a Repository this error message appears. This renderes the tool unusable.
I'm using Version 2.7.18106.03.

**Comment by jhueppauff** [comment]
seems to be connected #79

**Comment by jhueppauff** [comment]
latest PreRelease should fix this issue

**Comment by TclasenITVT** [comment]
Retested in Release 2.7.18111.03 seems to be fixed
