### ISSUE TITLE
Selecting a Repository will open the CRM Connection of the latest in the list

### ISSUE THREAD

**Issue by jhueppauff-itvt** [jhueppauff/Dynamics365-Customizing-Downloader#83]
Affected Version: 2.7

**Comment by jhueppauff-itvt** [comment]
Also seems to be the case in the 2.6 Version

**Comment by jhueppauff-itvt** [comment]
Starting download will fill in the local folder in the first connection. Somehow ordering seems to be broken completly

**Comment by jhueppauff** [comment]
Fix is in the current PreRelease. => 2.7
